---
- name: "systemd_helper | Make tmpfiles.d directory"
  ansible.builtin.file:
    path: "/etc/tmpfiles.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: "systemd_helper | Set facts about tmpfiles.d"
  ansible.builtin.set_fact:
    systemd_tmpfiles_create:
      "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] |
      community.general.json_query('[].create[].file_name') }}"
    systemd_tmpfiles_clean:
      "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] |
      community.general.json_query('[].clean[].file_name') }}"
    systemd_tmpfiles_remove:
      "{{ hostvars[inventory_hostname]['systemd_tmpfiles'] |
      community.general.json_query('[].remove[].file_name') }}"
- name: "systemd_helper | Find exists tmpfiles configuration files"
  ansible.builtin.find:
    paths: "/etc/tmpfiles.d"
    recurse: "no"
    file_type: "file"
    use_regex: "yes"
    patterns: "(.*).conf"
    excludes: "{{ (exclude_systemd_tmpfiles_create +
      exclude_systemd_tmpfiles_clean + exlucde_systemd_tmpfiles_remove) |
      default('[]') }}"
  register: "tmpfiles_find_result"
  when:
    - "hostvars[inventory_hostname]['systemd_tmpfiles'] |
       community.general.json_query(vars['tmpfiles_drop_exists']) is defined"
    - "hostvars[inventory_hostname]['systemd_tmpfiles'] |
       community.general.json_query(vars['tmpfiles_drop_exists']) == 'true'"
  vars:
    tmpfiles_drop_exists: "[] | map(&drop_exists || 'false', @) | [0]"
    exclude_systemd_tmpfiles_create: "{{ ((vars['systemd_tmpfiles_create'] |
      map('regex_replace', '^(.*)$', '\\1.conf')) | list()) | default([]) }}"
    exclude_systemd_tmpfiles_clean: "{{ ((vars['systemd_tmpfiles_clean'] |
      map('regex_replace', '^(.*)$', '\\1.conf')) | list()) | default([]) }}"
    exlucde_systemd_tmpfiles_remove: "{{ ((vars['systemd_tmpfiles_remove'] |
      map('regex_replace', '^(.*)$', '\\1.conf')) | list()) | default([]) }}"
- name: "systemd_helper | Delete exists tmpfiles configuration files"
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: "absent"
  loop: "{{ vars['tmpfiles_find_result']['files'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ item['path'] }}"
  when:
    - "vars['tmpfiles_find_result']['files'] is defined"
