---
- name: systemd_helper | Make modules-load.d directory
  file:
    path: "/etc/modules-load.d"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: systemd_helper | Set facts about modules-load.d
  set_fact:
    systemd_modules_load_create: "{{
      hostvars[inventory_hostname]['systemd_modules_load'] |
      json_query('[].modules_load[].file_name') }}"
- name: systemd_helper | Find exists modules-load configuration files
  find:
    paths: "/etc/modules-load.d"
    recurse: "no"
    file_type: "file"
    patterns: "(.*).conf"
    use_regex: "true"
  register: "modules_load_find_result"
  when:
  - "hostvars[inventory_hostname]['systemd_modules_load'] |
     json_query(vars['modules_load_drop_exists']) is defined"
  - "hostvars[inventory_hostname]['systemd_modules_load'] |
     json_query(vars['modules_load_drop_exists']) == 'true'"
  vars:
    modules_load_drop_exists: "[] | map(&drop_exists || 'false', @) | [0]"
- name: systemd_helper | Delete exists modules-load configuration files
  file:
    path: "{{ item.path }}"
    state: "absent"
  loop: "{{ vars['modules_load_find_result']['files'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.path }}"
  when:
  - "vars['modules_load_find_result']['files'] is defined"
